name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, Ajay!
    - uses: Ajay-MS/hello-world-action
      with:
        who-to-greet: 'Ajay Yadav'
      id: hello
