name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, Ajay2!
    - uses: Ajay-MS/hello-world-action@master
      with:
        action-type: 'SET_CONDITION'
        project-id: '008af12b-94a6-4015-8633-4f50cc02b9c0'
        feature-flag-name: 'Microsoft.FeatureFlagDemo.GreenBackground'
        feature-flag-condition: "- target: 'user'\n  op: '='\n  value: 'A5'"
      id: hello
