name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, Ajay2!
    - uses: Ajay-MS/hello-world-action@master
      with:
        action-type: 'GET-FEATURE-FLAGS'
        project-id: '11e16aac-0888-48a9-8894-26a717ff2b81'
      id: hello
