name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Feature flag rollout demo!
    - uses: Ajay-MS/hello-world-action@master
      with:
        action-type: 'SET_CONDITION'
        project-id: '008af12b-94a6-4015-8633-4f50cc02b9c0'
        feature-flag-name: 'Microsoft.FeatureFlagDemo.GreenBackground'
        feature-flag-condition: "- target: 'row'\n  op: '='\n  value: 'A'"
    - uses: Ajay-MS/hello-world-action@master
      with:
        action-type: 'TURN_ON'
        project-id: '008af12b-94a6-4015-8633-4f50cc02b9c0'
        feature-flag-name: 'Microsoft.FeatureFlagDemo.GreenBackground'
    - uses: Ajay-MS/hello-world-action@master
      with:
        action-type: 'SET_CONDITION'
        project-id: '008af12b-94a6-4015-8633-4f50cc02b9c0'
        feature-flag-name: 'Microsoft.FeatureFlagDemo.GreenBackground'
        feature-flag-condition: "- target: 'row'\n  op: '='\n  value: 'A' \n- target: 'userId'\n  op: '%'\n  value: '10'"
    - uses: Ajay-MS/hello-world-action@master
      with:
        action-type: 'SET_CONDITION'
        project-id: '008af12b-94a6-4015-8633-4f50cc02b9c0'
        feature-flag-name: 'Microsoft.FeatureFlagDemo.GreenBackground'
        feature-flag-condition: "- target: 'row'\n  op: '='\n  value: 'A' \n- target: 'userId'\n  op: '%'\n  value: '10' \n- target: 'row'\n  op: '='\n  value: 'B'"
    - uses: Ajay-MS/hello-world-action@master
      with:
        action-type: 'SET_CONDITION'
        project-id: '008af12b-94a6-4015-8633-4f50cc02b9c0'
        feature-flag-name: 'Microsoft.FeatureFlagDemo.GreenBackground'
        feature-flag-condition: "- target: 'row'\n  op: '='\n  value: 'A' \n- target: 'userId'\n  op: '%'\n  value: '30' \n- target: 'row'\n  op: '='\n  value: 'B'"
    - uses: Ajay-MS/hello-world-action@master
      with:
        action-type: 'SET_CONDITION'
        project-id: '008af12b-94a6-4015-8633-4f50cc02b9c0'
        feature-flag-name: 'Microsoft.FeatureFlagDemo.GreenBackground'
        feature-flag-condition: "- target: 'row'\n  op: '='\n  value: 'A' \n- target: 'userId'\n  op: '%'\n  value: '60' \n- target: 'row'\n  op: '='\n  value: 'B'"
    - uses: Ajay-MS/hello-world-action@master
      with:
        action-type: 'SET_CONDITION'
        project-id: '008af12b-94a6-4015-8633-4f50cc02b9c0'
        feature-flag-name: 'Microsoft.FeatureFlagDemo.GreenBackground'
        feature-flag-condition: "- target: 'row'\n  op: '='\n  value: 'A' \n- target: 'userId'\n  op: '%'\n  value: '100' \n- target: 'row'\n  op: '='\n  value: 'B'"
